export const FETCH_POKEMON_DATA = "FETCH_POKEMON_DATA";
export const GET_POKEMON_CARDS_REQUEST = "GET_POKEMON_CARDS_REQUEST";
export const GET_POKEMON_CARDS_SUCCESS = "GET_POKEMON_CARDS_SUCCESS";
export const GET_POKEMON_CARDS_ERROR = "GET_POKEMON_CARDS_ERROR";

export const FETCH_POKEMON_SUBTYPE = "FETCH_POKEMON_SUBTYPE";
export const GET_POKEMON_SUBTYPE_REQUEST = "GET_POKEMON_SUBTYPE_REQUEST";
export const GET_POKEMON_SUBTYPE_SUCCESS = "GET_POKEMON_SUBTYPE_SUCCESS";
export const GET_POKEMON_SUBTYPE_ERROR = "GET_POKEMON_SUBTYPE_ERROR";

export const FETCH_POKEMON_SUPERTYPE = "FETCH_POKEMON_SUPERTYPE";
export const GET_POKEMON_SUPERTYPE_REQUEST = "GET_POKEMON_SUPERTYPE_REQUEST";
export const GET_POKEMON_SUPERTYPE_SUCCESS = "GET_POKEMON_SUPERTYPE_SUCCESS";
export const GET_POKEMON_SUPERTYPE_ERROR = "GET_POKEMON_SUPERTYPE_ERROR";

export const FETCH_POKEMON_RARITY = "FETCH_POKEMON_RARITY";
export const GET_POKEMON_RARITY_REQUEST = "GET_POKEMON_RARITY_REQUEST";
export const GET_POKEMON_RARITY_SUCCESS = "GET_POKEMON_RARITY_SUCCESS";
export const GET_POKEMON_RARITY_ERROR = "GET_POKEMON_RARITY_ERROR";

export const SET_FILTER = "SET_FILTER";
